# Generated by Django 4.2.3 on 2023-07-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('referrer_bonus_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('referrer_max_bonus_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('referee_bonus_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=4)),
                ('referee_max_bonus_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
            ],
        ),
    ]
