# Generated by Django 4.2.3 on 2023-07-30 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_session_key_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
