# Generated by Django 4.2.3 on 2023-07-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_is_active_productvariant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
