# Generated by Django 4.2.3 on 2023-07-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productvariant_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
